### ISSUE TITLE
Form (formx) font seem much bigger on Linxu(ubuntu 22.04)

### ISSUE THREAD

**Issue by Amourspirit** [Amourspirit/python-ooouno-ex#150]
The fonts seem to be Bigger on Linux. I think some adjustment is needed to [build.py](/Amourspirit/python-ooouno-ex/blob/formx/ex/auto/writer/odev_build_form/build_form.py).
LibreOffice 7.4

Branch [formx](/Amourspirit/python-ooouno-ex/tree/formx)

Group boxes are cutting off text. Probably just needs to be shifted left and made wider.

Also I think the drop down list should be made wider.

I can make the adjustment if need be.

![image](https://user-images.githubusercontent.com/4193389/196026204-2e20eb1d-ae99-46ae-8983-323e9eef7a1a.png)

**Comment by flywire** [comment]
There was a PR waiting with text box_width, though the value needs to increase.

I wonder what sets font size.

**Comment by Amourspirit** [comment]
I am wondering what set the font myself.

Anyway I made the changes to the layout to make it a little bigger.

I tested on Windows and Ubuntu. Group boxes are slightly big on Windows but is good for an example.

Have another look at formx before I merge it.

**Comment by flywire** [comment]
Yes, that's good. Maybe the font and checkbox issue will get looked at later.
